FROM ubuntu:24.04

LABEL maintainer="pepemxl@gmail.com"

# Actualiza los paquetes del sistema e instala Python 3.11 y pip
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.11 python3.11-venv python3-pip && \
    apt-get clean

COPY requirements.txt /app/requirements.txt
COPY verificador.py /app/verificador.py

WORKDIR /app

# Instala las dependencias de Python
RUN python3.11 -m pip install --upgrade pip && \
    pip install -r requirements.txt

# Ejecuta el script verificador
CMD ["python3.11", "verificador.py"]
